### ISSUE TITLE
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by WoshiBoluo** [yiranran/Audio-driven-TalkingFace-HeadPose#36]
I have this problem in step 2 which is extracting the landmark:

Traceback (most recent call last):
  File "extract_frame1.py", line 64, in <module>
    detect_dir(mp4[:-4])
  File "extract_frame1.py", line 47, in detect_dir
    detect_image(imagename=file, savepath=file[:-4]+'.txt')
  File "extract_frame1.py", line 25, in detect_image
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by liyuli1997** [comment]
您好，您解决了吗
