### ISSUE TITLE
undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

### ISSUE THREAD

**Issue by 15211** [yiranran/Audio-driven-TalkingFace-HeadPose#48]
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/60fa6525d50100b7b5f2200eb3a7cc53/sandbox/processwrapper-sandbox/48/execroot/tf_mesh_renderer/bazel-out/k8-fastbuild/bin/mesh_renderer/mesh_renderer_test.runfiles/tf_mesh_renderer/mesh_renderer/mesh_renderer_test.py", line 26, in <module>
    import mesh_renderer
  File "/root/audio2/Deep3DFaceReconstruction/tf_mesh_renderer/mesh_renderer/mesh_renderer.py", line 24, in <module>
    import rasterize_triangles
  File "/root/audio2/Deep3DFaceReconstruction/tf_mesh_renderer/mesh_renderer/rasterize_triangles.py", line 29, in <module>
    'tf_mesh_renderer/mesh_renderer/kernels/rasterize_triangles_kernel.so'))
  File "/root/anaconda3/envs/audio2/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /root/audio2/Deep3DFaceReconstruction/tf_mesh_renderer/mesh_renderer/kernels/rasterize_triangles_kernel.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

请问有此问题的解决方法吗？
tf=1.14.0，已链接.so文件
尝试过更换bazel版本和gcc版本，未解决
更改-D_GLIBCXX_USE_CXX11_ABI=1，未解决

Can anyone offer a solution？
tf=1.14.0，i have changed bazel version and GCC version , but failed.
set -D_GLIBCXX_USE_CXX11_ABI=1, failed either

**Comment by jordanfranklin1** [comment]
Were you able to resolve the issue since it has been closed? If so, how did you do it? Thank you.

**Comment by lkh9908** [comment]
Having the same issue, did anyone manage to solve it?

**Comment by jordanfranklin1** [comment]
I was able to run the 'Build tf_mesh_renderer' section. Apparently, -D_GLIBCXX_USE_CXX11_ABI=1 should be used when using Tensorflow 1.15 or later. -D_GLIBCXX_USE_CXX11_ABI=0 should be used when using Tensorflow 1.14 or older. Since the Colab notebook uses Tensorflow 1.14, use -D_GLIBCXX_USE_CXX11_ABI=0 for line 4 of the 'Build tf_mesh_renderer' section.
