### ISSUE TITLE
RasterizeTriangles expects vertices to have shape (-1, 3). 

### ISSUE THREAD

**Issue by 15458wew** [yiranran/Audio-driven-TalkingFace-HeadPose#56]
Hello, thank you for opening up such a good job. I found the following problems during study, can you tell me a solution. Thanks you.

Use tf.where in 2.0, which has the same broadcast rule as np.where
2021-03-30 16:08:24.343185: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set. If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU. To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Traceback (most recent call last):
File "/home/research/weiwenqi/anaconda3/envs/snowflake_weiwenqi/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
return fn(*args)
File "/home/research/weiwenqi/anaconda3/envs/snowflake_weiwenqi/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
options, feed_dict, fetch_list, target_list, run_metadata)
File "/home/research/weiwenqi/anaconda3/envs/snowflake_weiwenqi/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: RasterizeTriangles expects vertices to have shape (-1, 3).
[[{{node while/RasterizeTriangles}}]]

**Comment by zoezhu** [comment]
I encountered the same error too, I solved this by chaning **def rasterize** as following:
`
# Deep3DFaceReconstruction/tf_mesh_renderer/mesh_renderer/rasterize_triangles.py

_MINIMUM_PERSPECTIVE_DIVIDE_THRESHOLD = 1e-6


def rasterize(world_space_vertices, attributes, triangles, camera_matrices,
              image_width, image_height, background_value):

  clip_space_vertices = camera_utils.transform_homogeneous(
      camera_matrices, world_space_vertices)
  clip_space_points_w = tf.maximum(
      tf.abs(clip_space_vertices[:, :, 3:4]),
      _MINIMUM_PERSPECTIVE_DIVIDE_THRESHOLD) * tf.sign(
          clip_space_vertices[:, :, 3:4])
  clip_space_vertices = (clip_space_vertices[:, :, 0:3] / clip_space_points_w)
  return rasterize_clip_space(clip_space_vertices, attributes, triangles,
                              image_width, image_height, background_value)
`
