### ISSUE TITLE
我在colab安装好环境之后,运行!python test_personalized.py 5_00006  31 0 实现第一个demo发现它并不能工作，请问作者有什么需要注意的吗？

### ISSUE THREAD

**Issue by liupeng678** [yiranran/Audio-driven-TalkingFace-HeadPose#7]
python atcnet_test1.py --device_ids 1 --model_name ../model/atcnet_pose0_con3/31/atcnet_lstm_99.pth --pose 1 --relativeframe 0 --sample_dir ../results/atcnet_pose0_con3/31/5_00006_99 --in_file ../audio/5_00006.wav
device 1
Traceback (most recent call last):
  File "atcnet_test1.py", line 117, in <module>
    test()
  File "atcnet_test1.py", line 85, in test
    state_dict = multi2single(config.model_name, 0)
  File "atcnet_test1.py", line 22, in multi2single
    checkpoint = torch.load(model_path)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '../model/atcnet_pose0_con3/31/atcnet_lstm_99.pth'
choose_bg_gexinghua2 19_news/31 5_00006 0 atcnet_pose0_con3/31/5_00006_99
../results/chosenbg/5_00006_19_news/31_atcnet_pose0_con3_31_5_00006_99/reassign
Traceback (most recent call last):
  File "test_personalized.py", line 66, in <module>
    bgdir = choose_bg_gexinghua2_reassign2('19_news/'+person, audiobasen, start, audiomodel, num=num, tran=pingyi, speed=speed)
  File "/content/drive/Shared drives/masterWork/Audio2Vdeio/Audio-driven-TalkingFace-HeadPose-master/Audio/code/choose_bg_gexinghua2_reassign.py", line 116, in choose_bg_gexinghua2_reassign2
    os.makedirs(tardir2)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '../results/chosenbg'

**Comment by yiranran** [comment]
> OSError: [Errno 30] Read-only file system: '../results/chosenbg’

Could you check your the file system permission for this folder  ‘Audio/results/chosenbg’
Maybe just use chmod can solve this problem...

**Comment by liupeng678** [comment]
thanks for your reply.  It doesn't have '../results/chosenbg' file . Maybe it is because matlab.I have another question about matlab .  I am not sure how install matlab in colab ,Did you try take code environment in google colab ? And  there has  question  about   other  library version.

**Comment by liupeng678** [comment]
I think it is amazing.Now I just want to run  2_00006.wav  demo in this project .But it is hard  because I am new coder.  Can you give me a  help about how to run in google colab. I have  300 yuan to pay for your time .(a college student is relatively poor。。。。)And it may  help for this  code to   spread.

**Comment by yiranran** [comment]
Here is an example demo in colab:
https://colab.research.google.com/drive/1gqcqTSAGAyj48n0fmApvSPG_43BzKP37

**Comment by jjandnn** [comment]
https://github.com/yiranran/Audio-driven-TalkingFace-HeadPose/issues/6#issuecomment-612992233
